name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pipenv==2023.12.0 wheel>=0.40.0
        pipenv sync --dev
    - name: Run tests
      run: |
        pipenv run coverage run --source=. -m pytest
        pipenv run coverage report -m --omit="*/tests/*"
